language: node_js
node_js:
  - 6
notifications:
  email: false
branches:
  only:
    - master
script:
  - npm run test
  - npm run build
after_success: 'npm test -- --coverage'
cache:
  directories:
    - node_modules
